"""
Epistemic Generator: Pulse AI.* → Functional inference code

This is the ONLY layer where LLM involvement is permitted.
It receives structured AST nodes (not raw text) and generates
code with strict constraints (temperature, schema, fallback).

Generated code:
- Reads the prompt file from disk
- Calls the AI provider (Claude API by default)
- Validates the response against the Zod schema (generated by Layer 2)
- Executes the declared fallback strategy on failure

v0.3 additions:
- Extracts _confidence from AI response when on_low_confidence declared
- Generates checkpoint trigger when confidence < threshold
- AI.reason() supported as a function type (same as scan, chain-of-thought intent)
"""

from __future__ import annotations

from epi.parser.ast_nodes import AICall, EpiProgram, Pulse


def generate_pulse_code(pulse: Pulse, program: EpiProgram, target: str = "nextjs") -> str:
    """Generate a functional Pulse implementation with AI calls, validation, and fallback."""
    entity = program.get_entity(pulse.input_entity)
    entity_name = entity.name if entity else pulse.input_entity

    if target == "nextjs":
        return _nextjs_pulse(pulse, entity_name, program)
    return _fastapi_pulse(pulse, entity_name, program)


# Keep backward compat — old name used by cli.py
generate_pulse_stub = generate_pulse_code


def _nextjs_pulse(pulse: Pulse, entity_name: str, program: EpiProgram) -> str:
    """Generate TypeScript Pulse with Claude API call, Zod validation, and fallback."""
    guard_comment = ""
    if pulse.guard_ref:
        guard_comment = f"// Guard: {pulse.guard_ref} (enforced at pipeline route level)\n"

    # Collect imports based on what the pulse needs
    imports = [
        'import Anthropic from "@anthropic-ai/sdk";',
        'import { readFileSync } from "fs";',
        'import { resolve } from "path";',
    ]

    # Add validator import if output references an entity field
    validator_import = _get_validator_import(pulse, program)
    if validator_import:
        imports.append(validator_import)

    imports_block = "\n".join(imports)

    # Generate AI call blocks
    ai_blocks = []
    for i, step in enumerate(pulse.process_steps):
        ai_blocks.append(_nextjs_ai_call(step, pulse, program, i))

    ai_code = "\n\n".join(ai_blocks)

    func_name = _to_camel(pulse.name)

    return (
        f"// Pulse: {pulse.name}\n"
        f"// Auto-generated by Epi Transpiler v0.3 (epistemic layer)\n"
        f"// Input: {entity_name}\n"
        f"{guard_comment}\n"
        f"{imports_block}\n\n"
        f"const client = new Anthropic();\n\n"
        f"export async function {func_name}(input: {entity_name}) {{\n"
        f"{ai_code}\n"
        f"}}\n"
    )


def _nextjs_ai_call(call: AICall, pulse: Pulse, program: EpiProgram, index: int) -> str:
    """Generate a single AI call block with validation, fallback, and confidence check."""
    temp = call.args.get("temperature", 0.7)
    max_tokens = call.args.get("max_tokens", 1024)
    confidence_threshold = call.args.get("confidence_threshold")

    # Prompt loading
    prompt_load = ""
    if call.prompt_file:
        prompt_path = call.prompt_file.replace("@prompts/", "prompts/")
        # v0.3: inject _confidence instruction when on_low_confidence is declared
        confidence_instruction = ""
        if call.on_low_confidence:
            confidence_instruction = (
                "\n    + \"\\\\n\\\\nIMPORTANT: Include a '_confidence' field (0.0-1.0) in your JSON response.\""
            )
        prompt_load = (
            f'  const promptPath = resolve(process.cwd(), "{prompt_path}");\n'
            f'  const systemPrompt = readFileSync(promptPath, "utf-8"){confidence_instruction};\n'
        )
    else:
        base_prompt = '"You are an AI assistant. Analyze the input and return a structured response."'
        if call.on_low_confidence:
            base_prompt = (
                '"You are an AI assistant. Analyze the input and return a structured JSON response. '
                'Include a \\"_confidence\\" field (0.0–1.0) for your confidence level."'
            )
        prompt_load = f'  const systemPrompt = {base_prompt};\n'

    # Source reference — normalise capitalisation: "Input.campo" → "input.campo"
    source = call.args.get("source", "input")
    if isinstance(source, str):
        if source == "Input":
            source = "input"
        elif source.startswith("Input."):
            source = "input." + source[6:]

    # Validator reference
    validator_ref = _get_validator_ref(pulse, program)

    # Validation block
    # NOTE: 'error' is only in scope inside the catch block above.
    # For the validation failure path we use parsed.error (Zod), not the caught exception.
    validation_block = ""
    if validator_ref:
        validation_block = (
            f"\n"
            f"  // Validate AI output against epistemic schema (Layer 2 constraint)\n"
            f"  const parsed = {validator_ref}.safeParse(aiResult);\n"
            f"  if (!parsed.success) {{\n"
            f"    console.error(`[Epi] Validation failed for {pulse.name}:`, parsed.error.issues);\n"
        )
        if call.fallback:
            # Pass parsed.error as the error source — avoids referencing 'error' outside catch
            fallback_code = _nextjs_fallback(call, indent=4, error_expr="parsed.error")
            validation_block += fallback_code
        else:
            validation_block += (
                f'    throw new Error(`Epistemic validation failed: ${{parsed.error.message}}`);\n'
            )
        validation_block += (
            f"  }}\n"
            f"\n"
            f"  return parsed.data;\n"
        )
    else:
        validation_block = f"\n  return aiResult;\n"

    # v0.3: confidence extraction and checkpoint trigger
    confidence_block = ""
    if call.on_low_confidence:
        threshold = confidence_threshold or 0.75
        strategy = call.on_low_confidence.strategy
        confidence_block = (
            f"\n"
            f"  // v0.3: Stochastic routing — extract confidence and check threshold\n"
            f"  let confidence = 0.5; // default if not provided\n"
            f"  if (typeof (aiResult as Record<string, unknown>)._confidence === 'number') {{\n"
            f"    confidence = (aiResult as Record<string, unknown>)._confidence as number;\n"
            f"    delete (aiResult as Record<string, unknown>)._confidence;\n"
            f"  }}\n"
            f"\n"
            f"  if (confidence < {threshold}) {{\n"
            f"    // Checkpoint.{strategy}: confidence below threshold — route for human review\n"
            f"    console.warn(`[Epi] Low confidence (${{confidence.toFixed(2)}} < {threshold}) in {pulse.name}. Routing to checkpoint.`);\n"
            f"    return {{\n"
            f'      _epi_checkpoint: true,\n'
            f'      _epi_strategy: "{strategy}",\n'
            f'      confidence,\n'
            f'      threshold: {threshold},\n'
            f"      partialResult: aiResult,\n"
            f"    }};\n"
            f"  }}\n"
        )

    # Build the AI call
    return (
        f"  // AI.{call.function}()\n"
        f"{prompt_load}"
        f"\n"
        f"  let aiResult: unknown;\n"
        f"  try {{\n"
        f"    const response = await client.messages.create({{\n"
        f'      model: "claude-sonnet-4-20250514",\n'
        f"      max_tokens: {int(max_tokens)},\n"
        f"      temperature: {temp},\n"
        f"      system: systemPrompt,\n"
        f"      messages: [\n"
        f"        {{\n"
        f'          role: "user",\n'
        f"          content: JSON.stringify({source}),\n"
        f"        }},\n"
        f"      ],\n"
        f"    }});\n"
        f"\n"
        f"    const text = response.content[0].type === 'text' ? response.content[0].text : '';\n"
        f"    aiResult = JSON.parse(text);\n"
        f"  }} catch (error) {{\n"
        f"    console.error(`[Epi] AI call failed for {pulse.name}:`, error);\n"
        + _nextjs_fallback(call, indent=4)
        + f"  }}\n"
        + confidence_block
        + validation_block
    )


def _nextjs_fallback(call: AICall, indent: int = 4, error_expr: str | None = None) -> str:
    """Generate fallback strategy code.

    error_expr: expression to use as the error source. Defaults to the caught 'error'
    variable (valid inside catch blocks). Pass "parsed.error" when called from a
    validation context where 'error' is not in scope.
    """
    pad = " " * indent
    if not call.fallback:
        return f'{pad}throw new Error("AI call failed and no fallback defined");\n'

    strategy = call.fallback.strategy
    params = call.fallback.params

    # Error message expression — safe to use in any context
    if error_expr:
        reason_expr = f'String({error_expr})'
    else:
        reason_expr = 'error instanceof Error ? error.message : "Unknown error"'

    if strategy == "ManualReview":
        queue = params.get("Queue", "default")
        return (
            f"{pad}// Fallback: ManualReview — route to human queue\n"
            f"{pad}return {{\n"
            f'{pad}  status: "pending_review",\n'
            f'{pad}  queue: "{queue}",\n'
            f'{pad}  reason: {reason_expr},\n'
            f'{pad}  timestamp: new Date().toISOString(),\n'
            f"{pad}}};\n"
        )
    elif strategy == "ReturnEmpty":
        return (
            f"{pad}// Fallback: ReturnEmpty\n"
            f"{pad}return null;\n"
        )
    elif strategy == "ReturnDefault":
        value = params.get("value", "null")
        return (
            f"{pad}// Fallback: ReturnDefault\n"
            f'{pad}return "{value}";\n'
        )
    elif strategy == "Retry":
        max_retries = params.get("max", "3")
        if error_expr:
            throw_expr = f'new Error({reason_expr})'
        else:
            throw_expr = 'error'
        return (
            f"{pad}// Fallback: Retry (handled at Pipeline level, max: {max_retries})\n"
            f"{pad}throw {throw_expr};\n"
        )
    elif strategy == "Escalate":
        target = params.get("to", "system")
        return (
            f"{pad}// Fallback: Escalate to {target}\n"
            f"{pad}return {{\n"
            f'{pad}  status: "escalated",\n'
            f'{pad}  escalated_to: "{target}",\n'
            f'{pad}  reason: {reason_expr},\n'
            f"{pad}}};\n"
        )
    else:
        return f'{pad}throw new Error("Unknown fallback strategy: {strategy}");\n'


def _fastapi_pulse(pulse: Pulse, entity_name: str, program: EpiProgram) -> str:
    """Generate Python Pulse with Anthropic SDK call, Pydantic validation, and fallback."""
    guard_comment = ""
    if pulse.guard_ref:
        guard_comment = f"# Guard: {pulse.guard_ref} (enforced at pipeline route level)\n"

    ai_blocks = []
    for step in pulse.process_steps:
        ai_blocks.append(_fastapi_ai_call(step, pulse))

    ai_code = "\n\n".join(ai_blocks)
    func_name = _to_snake(pulse.name)

    return (
        f"# Pulse: {pulse.name}\n"
        f"# Auto-generated by Epi Transpiler v0.3 (epistemic layer)\n"
        f"# Input: {entity_name}\n"
        f"{guard_comment}\n"
        f"import json\n"
        f"from pathlib import Path\n"
        f"from anthropic import Anthropic\n\n"
        f"client = Anthropic()\n\n\n"
        f"async def {func_name}(input_data: dict) -> dict:\n"
        f"{ai_code}\n"
    )


def _fastapi_ai_call(call: AICall, pulse: Pulse) -> str:
    """Generate a Python AI call block."""
    temp = call.args.get("temperature", 0.7)
    max_tokens = call.args.get("max_tokens", 1024)
    source = call.args.get("source", "input_data")
    confidence_threshold = call.args.get("confidence_threshold")

    prompt_load = ""
    if call.prompt_file:
        prompt_path = call.prompt_file.replace("@prompts/", "prompts/")
        confidence_instruction = ""
        if call.on_low_confidence:
            confidence_instruction = (
                '\n    system_prompt += "\\n\\nIMPORTANT: Include a \'_confidence\' field (0.0–1.0) in your JSON response."\n'
            )
        prompt_load = (
            f'    prompt_path = Path("{prompt_path}")\n'
            f'    system_prompt = prompt_path.read_text()\n'
            f'{confidence_instruction}'
        )
    else:
        prompt_load = (
            f'    system_prompt = "You are an AI assistant. Analyze the input and return structured JSON."\n'
        )

    fallback_code = _fastapi_fallback(call)

    # v0.3: confidence extraction
    confidence_block = ""
    if call.on_low_confidence:
        threshold = confidence_threshold or 0.75
        strategy = call.on_low_confidence.strategy
        confidence_block = (
            f"\n"
            f"        # v0.3: Stochastic routing — extract confidence\n"
            f"        confidence = ai_result.pop('_confidence', 0.5)\n"
            f"        if confidence < {threshold}:\n"
            f'            return {{\n'
            f'                "_epi_checkpoint": True,\n'
            f'                "_epi_strategy": "{strategy}",\n'
            f'                "confidence": confidence,\n'
            f'                "threshold": {threshold},\n'
            f'                "partial_result": ai_result,\n'
            f'            }}\n'
        )

    return (
        f"    # AI.{call.function}()\n"
        f"{prompt_load}"
        f"\n"
        f"    try:\n"
        f"        response = client.messages.create(\n"
        f'            model="claude-sonnet-4-20250514",\n'
        f"            max_tokens={int(max_tokens)},\n"
        f"            temperature={temp},\n"
        f"            system=system_prompt,\n"
        f'            messages=[{{"role": "user", "content": json.dumps({source})}}],\n'
        f"        )\n"
        f"        text = response.content[0].text\n"
        f"        ai_result = json.loads(text)\n"
        f"{confidence_block}"
        f"        return ai_result\n"
        f"    except Exception as e:\n"
        f'        print(f"[Epi] AI call failed for {pulse.name}: {{e}}")\n'
        f"{fallback_code}"
    )


def _fastapi_fallback(call: AICall) -> str:
    """Generate Python fallback code."""
    if not call.fallback:
        return '        raise\n'

    strategy = call.fallback.strategy
    params = call.fallback.params

    if strategy == "ManualReview":
        queue = params.get("Queue", "default")
        return (
            f"        # Fallback: ManualReview\n"
            f"        return {{\n"
            f'            "status": "pending_review",\n'
            f'            "queue": "{queue}",\n'
            f'            "reason": str(e),\n'
            f"        }}\n"
        )
    elif strategy == "ReturnEmpty":
        return "        # Fallback: ReturnEmpty\n        return None\n"
    elif strategy == "ReturnDefault":
        value = params.get("value", "None")
        return f'        # Fallback: ReturnDefault\n        return "{value}"\n'
    elif strategy == "Retry":
        return "        # Fallback: Retry (handled at Pipeline level)\n        raise\n"
    elif strategy == "Escalate":
        target = params.get("to", "system")
        return (
            f"        # Fallback: Escalate to {target}\n"
            f'        return {{"status": "escalated", "escalated_to": "{target}", "reason": str(e)}}\n'
        )
    else:
        return "        raise\n"


def _get_validator_import(pulse: Pulse, program: EpiProgram) -> str | None:
    """Generate import for the Zod validator if the Pulse outputs to an entity field."""
    if not pulse.output_ref or "." not in pulse.output_ref:
        return None
    entity_name = pulse.output_ref.split(".")[0]
    field_name = pulse.output_ref.split(".")[1]
    schema_name = f"{entity_name}{field_name[0].upper()}{field_name[1:]}Schema"
    kebab = _to_kebab(entity_name)
    return f'import {{ {schema_name} }} from "../validators/{kebab}";'


def _get_validator_ref(pulse: Pulse, program: EpiProgram) -> str | None:
    """Get the Zod validator schema name for the Pulse output."""
    if not pulse.output_ref or "." not in pulse.output_ref:
        return None
    entity_name = pulse.output_ref.split(".")[0]
    field_name = pulse.output_ref.split(".")[1]
    return f"{entity_name}{field_name[0].upper()}{field_name[1:]}Schema"


# ============================================================
# Naming utilities
# ============================================================

def _to_camel(name: str) -> str:
    parts = _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])

def _to_snake(name: str) -> str:
    parts = _split_pascal(name)
    return "_".join(p.lower() for p in parts)

def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)

def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
