"""
Epistemic Generator: Pulse AI.* → Code via LLM

This is the ONLY layer where LLM involvement is permitted.
It receives structured AST nodes (not raw text) and generates
code with strict constraints (temperature, schema, fallback).

TODO: Implement LLM-backed generation via Claude API.
      For now, generates deterministic stubs with validation schemas.
"""

from __future__ import annotations

from epi.parser.ast_nodes import AICall, EpiProgram, Pulse


def generate_pulse_stub(pulse: Pulse, program: EpiProgram, target: str = "nextjs") -> str:
    """Generate a stub implementation for a Pulse with AI calls."""
    entity = program.get_entity(pulse.input_entity)
    entity_name = entity.name if entity else pulse.input_entity

    ai_calls_code = []
    for step in pulse.process_steps:
        ai_calls_code.append(_generate_ai_call_stub(step, target))

    if target == "nextjs":
        return _nextjs_pulse_stub(pulse, entity_name, ai_calls_code)
    return _fastapi_pulse_stub(pulse, entity_name, ai_calls_code)


def _generate_ai_call_stub(call: AICall, target: str) -> str:
    prompt_line = ""
    if call.prompt_file:
        prompt_line = f'  // Prompt loaded from: {call.prompt_file}\n'

    temp = call.args.get("temperature", 0.7)
    max_tokens = call.args.get("max_tokens", 1000)

    fallback_line = ""
    if call.fallback:
        fallback_line = f"  // Fallback: {call.fallback.strategy}({call.fallback.params})\n"

    return (
        f"  // AI.{call.function}()\n"
        f"{prompt_line}"
        f"  // temperature: {temp}, max_tokens: {max_tokens}\n"
        f"{fallback_line}"
        f"  // TODO: Replace stub with LLM call via epistemic generator\n"
        f'  const result = {{ status: "pending_epistemic_generation" }};\n'
    )


def _nextjs_pulse_stub(pulse: Pulse, entity_name: str, ai_code: list[str]) -> str:
    guard_comment = ""
    if pulse.guard_ref:
        guard_comment = f"// Guard: {pulse.guard_ref} (enforced at pipeline route level)\n"

    return (
        f"// Pulse: {pulse.name}\n"
        f"// Auto-generated by Epi Transpiler v0.2 (epistemic stub)\n"
        f"// Input: {entity_name}\n"
        f"{guard_comment}\n"
        f"export async function {_to_camel(pulse.name)}(input: {entity_name}) {{\n"
        + "\n".join(ai_code)
        + "\n  return result;\n"
        f"}}\n"
    )


def _fastapi_pulse_stub(pulse: Pulse, entity_name: str, ai_code: list[str]) -> str:
    return (
        f"# Pulse: {pulse.name}\n"
        f"# Auto-generated by Epi Transpiler v0.2 (epistemic stub)\n"
        f"# Input: {entity_name}\n\n"
        f"async def {_to_snake(pulse.name)}(input: {entity_name}):\n"
        + "\n".join(ai_code).replace("  //", "    #").replace("  const", "    ")
        + '\n    return {"status": "pending_epistemic_generation"}\n'
    )


def _to_camel(name: str) -> str:
    parts = _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])

def _to_snake(name: str) -> str:
    parts = _split_pascal(name)
    return "_".join(p.lower() for p in parts)

def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)

def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
