"""
Epistemic Generator: Lens Mood → UI via LLM

TODO: Implement LLM-backed UI generation from Mood strings.
      For now, generates deterministic component stubs.
"""

from __future__ import annotations

from epi.parser.ast_nodes import Lens, Widget


def generate_lens_stub(lens: Lens, target: str = "nextjs") -> str:
    """Generate a stub UI component from a Lens declaration."""
    if target == "nextjs":
        return _nextjs_lens_stub(lens)
    return f"# Lens: {lens.name} — target '{target}' not yet supported\n"


def _nextjs_lens_stub(lens: Lens) -> str:
    mood_comment = f"  // Mood: {lens.mood}\n" if lens.mood else ""
    inject_block = ""
    if lens.inject:
        inject_block = (
            f"\n      {{/* Escape Hatch — injected raw HTML */}}\n"
            f"      <div dangerouslySetInnerHTML={{{{ __html: `{lens.inject}` }}}} />\n"
        )

    widgets = "\n".join(f"      {_widget_to_jsx(w)}" for w in lens.display)

    return (
        f"// Lens: {lens.name}\n"
        f"// Auto-generated by Epi Transpiler v0.2 (epistemic stub)\n"
        f"// TODO: Apply Mood styling via LLM\n\n"
        f"'use client';\n\n"
        f"export default function {lens.name}() {{\n"
        f"{mood_comment}"
        f"  return (\n"
        f"    <div className=\"epi-lens epi-lens--{_to_kebab(lens.name)}\">\n"
        f"{widgets}"
        f"{inject_block}"
        f"    </div>\n"
        f"  );\n"
        f"}}\n"
    )


def _widget_to_jsx(widget: Widget) -> str:
    wtype = widget.widget_type
    entity = widget.args.get("entity", next(iter(widget.args), ""))

    trigger_attr = ""
    if widget.trigger:
        trigger_attr = f' onClick={{() => trigger("{widget.trigger.pulse_name}")}}'

    if wtype == "Table":
        cols = widget.args.get("columns", [])
        cols_str = ", ".join(f'"{c}"' for c in cols) if isinstance(cols, list) else ""
        return f"<{wtype}Component entity=\"{entity}\" columns={{[{cols_str}]}} />"
    elif wtype == "Form":
        return f"<{wtype}Component entity=\"{entity}\" />"
    elif wtype == "Button":
        label = next(
            (v for k, v in widget.args.items() if isinstance(v, str) and k != "entity"),
            wtype,
        )
        return f"<button{trigger_attr}>{label}</button>"
    else:
        return f"<{wtype}Component />"


def _to_kebab(name: str) -> str:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return "-".join(p.lower() for p in parts)
