"""
Epistemic Generator: Trace → Inspect/Resume infrastructure

Generates three artefacts for each Pulse with Traces:

1. lib/trace-store.ts        — in-memory state store (swap for Redis/DB in prod)
2. traces/{pulse}/{trace}.ts — trace execution with confidence extraction
3. app/api/traces/{pulse}/[traceId]/inspect/route.ts
4. app/api/traces/{pulse}/[traceId]/resume/route.ts

Design rationale:
- Inspect route: Professor (or any authorized role) can read intermediate
  reasoning steps BEFORE the AI sees subsequent inputs.
- Resume route: After review, Professor approves or corrects the reasoning.
  The correction becomes the context for the next Trace in the Pulse.
- Confidence is extracted from the AI response via a mandatory _confidence
  field injected into the system prompt. This implements Dante Barone's
  stochastic routing: low confidence → automatic pause → human review.

Source: Rosa (epistemic breakpoints) + Dante (stochastic routing).
"""

from __future__ import annotations

from epi.parser.ast_nodes import EpiProgram, Pulse, TraceStep


# ============================================================
# Public API
# ============================================================

def generate_trace_store() -> str:
    """Generate lib/trace-store.ts — persistent state for paused traces."""
    return """\
// lib/trace-store.ts
// Auto-generated by Epi Transpiler v0.3
//
// In-memory trace state store for epistemic checkpoints.
// PRODUCTION NOTE: Replace Map with Redis (ioredis) or a Prisma model.
// The interface contract (saveTrace, getTrace, updateTrace) stays the same.

export interface TraceState {
  traceId: string;
  pulseName: string;
  traceName: string;
  status: "running" | "paused" | "completed" | "error";
  /** Fields declared in Expose: — surfaced for human inspection */
  exposedFields: Record<string, unknown>;
  /** Raw AI output before any correction */
  rawOutput?: unknown;
  /** Confidence extracted from AI response (0.0 – 1.0) */
  confidence: number;
  /** Threshold below which this trace was paused */
  confidenceThreshold?: number;
  pausedAt?: string;
  /** User ID of the reviewer who approved/corrected */
  resumedBy?: string;
  /** Human correction injected as context into the next trace */
  humanCorrection?: Record<string, unknown>;
  createdAt: string;
}

const store = new Map<string, TraceState>();

export function saveTrace(state: TraceState): void {
  store.set(state.traceId, state);
}

export function getTrace(traceId: string): TraceState | undefined {
  return store.get(traceId);
}

export function updateTrace(traceId: string, patch: Partial<TraceState>): void {
  const existing = store.get(traceId);
  if (existing) {
    store.set(traceId, { ...existing, ...patch });
  }
}

export function listPausedTraces(pulseName?: string): TraceState[] {
  return Array.from(store.values()).filter(
    (s) => s.status === "paused" && (!pulseName || s.pulseName === pulseName)
  );
}
"""


def generate_trace_execution(pulse: Pulse, trace: TraceStep, program: EpiProgram) -> str:
    """Generate a trace execution module for a single TraceStep."""
    entity = program.get_entity(pulse.input_entity)
    entity_name = entity.name if entity else pulse.input_entity

    pulse_kebab = _to_kebab(pulse.name)
    trace_kebab = _to_kebab(trace.name)
    trace_camel = _to_camel(trace.name)
    pulse_pascal = pulse.name

    call = trace.ai_call
    temp = call.args.get("temperature", 0.3)
    max_tokens = call.args.get("max_tokens", 1024)
    confidence_threshold = call.args.get("confidence_threshold", 0.75)

    # Determine if this trace has a conditional checkpoint (on_low_confidence)
    has_conditional_checkpoint = call.on_low_confidence is not None
    checkpoint_strategy = (
        call.on_low_confidence.strategy if call.on_low_confidence else "ReviewRequired"
    )

    # Determine if this trace has an unconditional checkpoint (always pauses)
    has_unconditional_checkpoint = trace.checkpoint is not None

    # Prompt loading block
    if call.prompt_file:
        prompt_path = call.prompt_file.replace("@prompts/", "prompts/")
        confidence_note = "\\n\\nIMPORTANT: Your response MUST be valid JSON. Include a '_confidence' field (0.0-1.0) indicating your confidence in the output."
        prompt_block = (
            f'  const promptPath = resolve(process.cwd(), "{prompt_path}");\n'
            f'  const systemPrompt = readFileSync(promptPath, "utf-8") + "{confidence_note}";\n'
        )
    else:
        prompt_block = (
            '  const systemPrompt =\n'
            '    "You are a reasoning assistant. Analyze the input step by step. " +\n'
            '    "Return valid JSON with a \'_confidence\' field (0.0-1.0) for your confidence level.";\n'
        )

    # Source reference
    source = call.args.get("source", "input")
    if isinstance(source, str) and source.startswith("Input."):
        source = f"input.{source[6:]}"
    elif source == "Input":
        source = "input"

    # Expose fields extraction
    expose_fields = [e.split(".")[-1] for e in trace.expose]
    expose_js = ", ".join(f'"{f}"' for f in expose_fields) if expose_fields else ""
    if expose_js:
        expose_block = (
            f"  const exposedFields: Record<string, unknown> = {{}};\n"
            f"  const exposeKeys = [{expose_js}];\n"
            f"  for (const key of exposeKeys) {{\n"
            f"    if ((rawOutput as Record<string, unknown>)[key] !== undefined) {{\n"
            f"      exposedFields[key] = (rawOutput as Record<string, unknown>)[key];\n"
            f"    }}\n"
            f"  }}\n"
        )
    else:
        expose_block = "  const exposedFields: Record<string, unknown> = {};\n"

    # Checkpoint logic
    checkpoint_condition = ""
    if has_conditional_checkpoint and has_unconditional_checkpoint:
        checkpoint_condition = "  const shouldPause = true; // unconditional Checkpoint declared\n"
    elif has_conditional_checkpoint:
        checkpoint_condition = f"  const shouldPause = confidence < {confidence_threshold}; // on_low_confidence\n"
    elif has_unconditional_checkpoint:
        checkpoint_condition = "  const shouldPause = true; // unconditional Checkpoint declared\n"
    else:
        checkpoint_condition = "  const shouldPause = false;\n"

    return (
        f"// Trace: {trace.name} (Pulse: {pulse.name})\n"
        f"// Auto-generated by Epi Transpiler v0.3 (epistemic layer)\n"
        f"// Input: {entity_name}\n"
        f"// Checkpoint strategy: {checkpoint_strategy if (has_conditional_checkpoint or has_unconditional_checkpoint) else 'none'}\n"
        f"\n"
        f'import Anthropic from "@anthropic-ai/sdk";\n'
        f'import {{ readFileSync }} from "fs";\n'
        f'import {{ resolve }} from "path";\n'
        f'import {{ randomUUID }} from "crypto";\n'
        f'import {{ saveTrace, getTrace, updateTrace, TraceState }} from "../../lib/trace-store";\n'
        f"\n"
        f"const client = new Anthropic();\n"
        f"\n"
        f"export interface {trace.name}Result {{\n"
        f"  traceId: string;\n"
        f'  status: "completed" | "paused";\n'
        f"  output?: unknown;\n"
        f"  exposedFields: Record<string, unknown>;\n"
        f"  confidence: number;\n"
        f"}}\n"
        f"\n"
        f"export async function execute{trace.name}(\n"
        f"  input: {entity_name},\n"
        f"  previousContext?: unknown,\n"
        f"  sessionUserId?: string\n"
        f"): Promise<{trace.name}Result> {{\n"
        f"  const traceId = randomUUID();\n"
        f"  const CONFIDENCE_THRESHOLD = {confidence_threshold};\n"
        f"\n"
        f"  saveTrace({{\n"
        f'    traceId,\n'
        f'    pulseName: "{pulse_pascal}",\n'
        f'    traceName: "{trace.name}",\n'
        f'    status: "running",\n'
        f'    exposedFields: {{}},\n'
        f'    confidence: 0,\n'
        f'    confidenceThreshold: CONFIDENCE_THRESHOLD,\n'
        f'    createdAt: new Date().toISOString(),\n'
        f"  }});\n"
        f"\n"
        f"{prompt_block}\n"
        f"  // Inject previous trace context if available\n"
        f"  const userContent = previousContext\n"
        f"    ? JSON.stringify({{ input: {source}, context: previousContext }})\n"
        f"    : JSON.stringify({source});\n"
        f"\n"
        f"  let rawOutput: unknown;\n"
        f"  let confidence = 0;\n"
        f"\n"
        f"  try {{\n"
        f"    const response = await client.messages.create({{\n"
        f'      model: "claude-sonnet-4-20250514",\n'
        f"      max_tokens: {int(max_tokens)},\n"
        f"      temperature: {temp},\n"
        f"      system: systemPrompt,\n"
        f"      messages: [{{ role: \"user\", content: userContent }}],\n"
        f"    }});\n"
        f"\n"
        f"    const text = response.content[0].type === \"text\" ? response.content[0].text : \"{{}}\";\n"
        f"    rawOutput = JSON.parse(text);\n"
        f"\n"
        f"    // Extract _confidence (Epi epistemic contract)\n"
        f"    if (typeof (rawOutput as Record<string, unknown>)._confidence === \"number\") {{\n"
        f"      confidence = (rawOutput as Record<string, unknown>)._confidence as number;\n"
        f"      delete (rawOutput as Record<string, unknown>)._confidence;\n"
        f"    }}\n"
        f"\n"
        f"  }} catch (error) {{\n"
        f'    console.error(`[Epi] Trace {trace.name} failed:`, error);\n'
        f"    updateTrace(traceId, {{ status: \"error\" }});\n"
        f"    return {{ traceId, status: \"paused\", exposedFields: {{}}, confidence: 0 }};\n"
        f"  }}\n"
        f"\n"
        f"{expose_block}\n"
        f"{checkpoint_condition}\n"
        f"  if (shouldPause) {{\n"
        f"    updateTrace(traceId, {{\n"
        f'      status: "paused",\n'
        f"      exposedFields,\n"
        f"      confidence,\n"
        f"      rawOutput,\n"
        f"      pausedAt: new Date().toISOString(),\n"
        f"    }});\n"
        f"    return {{ traceId, status: \"paused\", exposedFields, confidence }};\n"
        f"  }}\n"
        f"\n"
        f"  updateTrace(traceId, {{\n"
        f'    status: "completed",\n'
        f"    exposedFields,\n"
        f"    confidence,\n"
        f"    rawOutput,\n"
        f"  }});\n"
        f"  return {{ traceId, status: \"completed\", output: rawOutput, exposedFields, confidence }};\n"
        f"}}\n"
    )


def generate_trace_routes(pulse: Pulse, program: EpiProgram) -> dict[str, str]:
    """Generate /inspect and /resume route files for a Pulse with Traces."""
    pulse_kebab = _to_kebab(pulse.name)
    files: dict[str, str] = {}

    # Collect authorized roles from guard
    guard_role = "Professor"
    if pulse.guard_ref:
        guard = program.get_guard(pulse.guard_ref.split(".")[-1])
        if guard and guard.conditions:
            for cond in guard.conditions:
                if "Role" in cond.left:
                    guard_role = cond.right

    # /inspect route
    files[f"app/api/traces/{pulse_kebab}/[traceId]/inspect/route.ts"] = _inspect_route(pulse, guard_role)
    # /resume route  (single [traceId] segment — no double slash)
    files[f"app/api/traces/{pulse_kebab}/[traceId]/resume/route.ts"] = _resume_route(pulse, guard_role)

    return files


def generate_all_traces(program: EpiProgram) -> dict[str, str]:
    """Generate all trace artefacts for an EpiProgram.

    Returns {filename: content} for the CLI to write.
    """
    files: dict[str, str] = {}

    has_any_traces = any(p.has_traces for p in program.pulses)
    if not has_any_traces:
        return files

    # Shared store (generated once)
    files["lib/trace-store.ts"] = generate_trace_store()

    for pulse in program.pulses:
        if not pulse.has_traces:
            continue

        pulse_kebab = _to_kebab(pulse.name)

        for trace in pulse.traces:
            trace_kebab = _to_kebab(trace.name)
            content = generate_trace_execution(pulse, trace, program)
            files[f"traces/{pulse_kebab}/{trace_kebab}.ts"] = content

        route_files = generate_trace_routes(pulse, program)
        files.update(route_files)

    return files


# ============================================================
# Route templates
# ============================================================

def _inspect_route(pulse: Pulse, guard_role: str) -> str:
    pulse_pascal = pulse.name
    return (
        f"// Inspect route — Trace epistemic state\n"
        f"// Auto-generated by Epi Transpiler v0.3\n"
        f"// Authorized role: {guard_role}\n"
        f"//\n"
        f"// GET /api/traces/{_to_kebab(pulse.name)}/[traceId]/inspect\n"
        f"// Returns the current TraceState including exposed reasoning fields.\n"
        f"// Use this endpoint to read the AI's intermediate reasoning\n"
        f"// before deciding whether to approve or correct it.\n"
        f"\n"
        f'import {{ NextRequest, NextResponse }} from "next/server";\n'
        f'import {{ getServerSession }} from "next-auth";\n'
        f'import {{ getTrace }} from "../../../../../lib/trace-store";\n'
        f"\n"
        f"export async function GET(\n"
        f"  request: NextRequest,\n"
        f"  {{ params }}: {{ params: {{ traceId: string }} }}\n"
        f") {{\n"
        f'  const session = await getServerSession();\n'
        f'  if (!session) {{\n'
        f'    return NextResponse.json({{ error: "Unauthorized" }}, {{ status: 401 }});\n'
        f'  }}\n'
        f"\n"
        f"  const state = getTrace(params.traceId);\n"
        f"  if (!state) {{\n"
        f'    return NextResponse.json({{ error: "Trace not found" }}, {{ status: 404 }});\n'
        f"  }}\n"
        f"\n"
        f"  return NextResponse.json({{\n"
        f"    traceId: state.traceId,\n"
        f"    pulseName: state.pulseName,\n"
        f"    traceName: state.traceName,\n"
        f"    status: state.status,\n"
        f"    exposedFields: state.exposedFields,\n"
        f"    confidence: state.confidence,\n"
        f"    confidenceThreshold: state.confidenceThreshold,\n"
        f"    pausedAt: state.pausedAt,\n"
        f"  }});\n"
        f"}}\n"
    )


def _resume_route(pulse: Pulse, guard_role: str) -> str:
    pulse_kebab = _to_kebab(pulse.name)
    # Build imports for all trace execution modules
    trace_imports = "\n".join(
        f'import {{ execute{t.name} }} from "../../../../../traces/{pulse_kebab}/{_to_kebab(t.name)}";'
        for t in pulse.traces
    )
    # Build dispatch map
    dispatch_entries = "\n".join(
        f'    "{t.name}": execute{t.name},'
        for t in pulse.traces
    )

    return (
        f"// Resume route — Continue paused trace after human review\n"
        f"// Auto-generated by Epi Transpiler v0.3\n"
        f"// Authorized role: {guard_role}\n"
        f"//\n"
        f"// POST /api/traces/{pulse_kebab}/[traceId]/resume\n"
        f"// Body: {{ correction?: Record<string, unknown> }}\n"
        f"//\n"
        f"// If correction is provided, it replaces the AI's raw output\n"
        f"// and becomes the context for the next Trace in the Pulse.\n"
        f"// If no correction, the original AI output is accepted as-is.\n"
        f"\n"
        f'import {{ NextRequest, NextResponse }} from "next/server";\n'
        f'import {{ getServerSession }} from "next-auth";\n'
        f'import {{ getTrace, updateTrace }} from "../../../../../lib/trace-store";\n'
        f"{trace_imports}\n"
        f"\n"
        f"export async function POST(\n"
        f"  request: NextRequest,\n"
        f"  {{ params }}: {{ params: {{ traceId: string }} }}\n"
        f") {{\n"
        f"  const session = await getServerSession();\n"
        f'  if (!session) {{\n'
        f'    return NextResponse.json({{ error: "Unauthorized" }}, {{ status: 401 }});\n'
        f'  }}\n'
        f"\n"
        f"  const state = getTrace(params.traceId);\n"
        f"  if (!state) {{\n"
        f'    return NextResponse.json({{ error: "Trace not found" }}, {{ status: 404 }});\n'
        f"  }}\n"
        f'  if (state.status !== "paused") {{\n'
        f'    return NextResponse.json({{ error: "Trace is not paused", status: state.status }}, {{ status: 400 }});\n'
        f"  }}\n"
        f"\n"
        f"  const body = await request.json().catch(() => ({{}}));\n"
        f"  const correction = body.correction ?? null;\n"
        f'  const resumedBy = (session as {{ user?: {{ email?: string }} }}).user?.email ?? "unknown";\n'
        f"\n"
        f"  // Accept correction or original AI output\n"
        f"  const acceptedOutput = correction ?? state.rawOutput;\n"
        f"\n"
        f"  updateTrace(params.traceId, {{\n"
        f'    status: "completed",\n'
        f"    resumedBy,\n"
        f"    humanCorrection: correction ?? undefined,\n"
        f"  }});\n"
        f"\n"
        f"  return NextResponse.json({{\n"
        f"    success: true,\n"
        f"    traceId: params.traceId,\n"
        f"    resumedBy,\n"
        f"    acceptedOutput,\n"
        f"    corrected: correction !== null,\n"
        f"  }});\n"
        f"}}\n"
    )


# ============================================================
# Naming utilities
# ============================================================

def _to_camel(name: str) -> str:
    parts = _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
