// Pipeline: FluxoAvaliacaoPedagogica
// Auto-generated by Epi Transpiler v0.2
// Flow: AvaliarRespostaAluno -> NotificarAluno

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { soProfessores } from '../../middleware/so-professores';
import { avaliarRespostaAluno } from '../../pulses/avaliar-resposta-aluno';
import { notificarAluno } from '../../pulses/notificar-aluno';

const MAX_RETRIES = 2;

async function executePipeline(input: unknown, session: unknown) {
    // Step 1: AvaliarRespostaAluno
    await soProfessores(session);
    const avaliarRespostaAlunoResult = await avaliarRespostaAluno(input);

    // Step 2: NotificarAluno
    const notificarAlunoResult = await notificarAluno(avaliarRespostaAlunoResult);

    return notificarAlunoResult;
}

export async function POST(request: NextRequest) {
  const input = await request.json();
  const session = await getServerSession();

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const result = await executePipeline(input, session);
      return NextResponse.json({ success: true, data: result });
    } catch (error) {
      if (attempt === MAX_RETRIES) {
        return NextResponse.json(
          { error: 'Pipeline failed after retries', pipeline: 'FluxoAvaliacaoPedagogica' },
          { status: 500 },
        );
      }
      await new Promise(r => setTimeout(r, Math.pow(2, attempt) * 1000));
    }
  }
}
