// Guard: ProfessorOuAdmin
// Auto-generated by Epi Transpiler v0.2
export function professorOuAdmin(session: Session) {
  if (session?.user?.role !== "Professor") {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }
  if (session?.user?.role !== "Admin") {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }
}
