// Guard: SoProfessores
// Auto-generated by Epi Transpiler v0.2
export function soProfessores(session: Session) {
  if (session?.user?.role !== "Professor") {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }
}
