// Inspect route — Trace epistemic state
// Auto-generated by Epi Transpiler v0.3
// Authorized role: Professor
//
// GET /api/traces/avaliar-resposta-aluno/[traceId]/inspect
// Returns the current TraceState including exposed reasoning fields.
// Use this endpoint to read the AI's intermediate reasoning
// before deciding whether to approve or correct it.

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { getTrace } from "../../../../../lib/trace-store";

export async function GET(
  request: NextRequest,
  { params }: { params: { traceId: string } }
) {
  const session = await getServerSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const state = getTrace(params.traceId);
  if (!state) {
    return NextResponse.json({ error: "Trace not found" }, { status: 404 });
  }

  return NextResponse.json({
    traceId: state.traceId,
    pulseName: state.pulseName,
    traceName: state.traceName,
    status: state.status,
    exposedFields: state.exposedFields,
    confidence: state.confidence,
    confidenceThreshold: state.confidenceThreshold,
    pausedAt: state.pausedAt,
  });
}
