"""
Tests for Epi code generators — deterministic (Layer 2) and epistemic (Layer 3).
"""

from pathlib import Path

import pytest

from epi.parser.builder import parse_epi
from epi.generators.deterministic.prisma import generate_prisma
from epi.generators.deterministic.middleware import generate_middleware
from epi.generators.deterministic.routes import generate_routes
from epi.generators.epistemic.ai_scan import generate_pulse_stub
from epi.generators.epistemic.lens_mood import generate_lens_stub


EXAMPLES_DIR = Path(__file__).parent.parent / "examples"


@pytest.fixture(scope="module")
def contrato_program():
    source = (EXAMPLES_DIR / "contrato.epi").read_text()
    return parse_epi(source)


# ============================================================
# Prisma Generator (Layer 2)
# ============================================================

class TestPrismaGenerator:
    def test_generates_valid_prisma(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "model Contrato {" in output
        assert "model Advogado {" in output

    def test_rigid_uuid_auto(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "id String @id @default(uuid())" in output

    def test_rigid_datetime_auto(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "criado_em DateTime @default(now())" in output

    def test_rigid_decimal(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "valor Decimal" in output

    def test_epistemic_field_annotation(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "risco String // @epi:epistemic AI.Enum(Alto, Medio, Baixo)" in output

    def test_epistemic_text_annotation(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "especialidade String // @epi:epistemic AI.Text" in output

    def test_header_present(self, contrato_program):
        output = generate_prisma(contrato_program)
        assert "Auto-generated by Epi Transpiler v0.2" in output
        assert 'provider = "postgresql"' in output


# ============================================================
# Middleware Generator (Layer 2)
# ============================================================

class TestMiddlewareGenerator:
    def test_generates_nextjs_middleware(self, contrato_program):
        files = generate_middleware(contrato_program, "nextjs")
        assert "middleware/somente-advogados.ts" in files
        assert "middleware/somente-admin.ts" in files

    def test_guard_function_name(self, contrato_program):
        files = generate_middleware(contrato_program, "nextjs")
        content = files["middleware/somente-advogados.ts"]
        assert "export function somenteAdvogados" in content

    def test_guard_checks_role(self, contrato_program):
        files = generate_middleware(contrato_program, "nextjs")
        content = files["middleware/somente-advogados.ts"]
        assert 'role !== "Lawyer"' in content

    def test_guard_returns_403(self, contrato_program):
        files = generate_middleware(contrato_program, "nextjs")
        content = files["middleware/somente-advogados.ts"]
        assert "status: 403" in content

    def test_generates_fastapi_dependency(self, contrato_program):
        files = generate_middleware(contrato_program, "fastapi")
        assert "dependencies/somente_advogados.py" in files
        content = files["dependencies/somente_advogados.py"]
        assert "HTTPException" in content


# ============================================================
# Routes Generator (Layer 2)
# ============================================================

class TestRoutesGenerator:
    def test_generates_route_file(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        assert "app/api/analisar-contrato/route.ts" in files

    def test_route_imports_pulses(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        content = files["app/api/analisar-contrato/route.ts"]
        assert "import { extrairRisco }" in content
        assert "import { gerarResumo }" in content
        assert "import { notificar }" in content

    def test_route_imports_guards(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        content = files["app/api/analisar-contrato/route.ts"]
        assert "import { somenteAdvogados }" in content

    def test_route_chains_results(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        content = files["app/api/analisar-contrato/route.ts"]
        # Step 2 receives result from step 1
        assert "gerarResumo(extrairRiscoResult)" in content
        # Step 3 receives result from step 2
        assert "notificar(gerarResumoResult)" in content

    def test_route_has_retry(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        content = files["app/api/analisar-contrato/route.ts"]
        assert "MAX_RETRIES = 3" in content
        assert "for (let attempt" in content
        assert "Math.pow(2, attempt)" in content  # exponential backoff

    def test_route_has_error_handling(self, contrato_program):
        files = generate_routes(contrato_program, "nextjs")
        content = files["app/api/analisar-contrato/route.ts"]
        assert "catch (error)" in content
        assert "Pipeline failed after retries" in content


# ============================================================
# Pulse Stub Generator (Layer 3)
# ============================================================

class TestPulseStubGenerator:
    def test_generates_function(self, contrato_program):
        pulse = contrato_program.get_pulse("ExtrairRisco")
        output = generate_pulse_stub(pulse, contrato_program, "nextjs")
        assert "export async function extrairRisco" in output

    def test_includes_ai_metadata(self, contrato_program):
        pulse = contrato_program.get_pulse("ExtrairRisco")
        output = generate_pulse_stub(pulse, contrato_program, "nextjs")
        assert "AI.scan()" in output
        assert "temperature: 0.1" in output
        assert "@prompts/legal_scan.md" in output

    def test_guard_as_comment(self, contrato_program):
        pulse = contrato_program.get_pulse("ExtrairRisco")
        output = generate_pulse_stub(pulse, contrato_program, "nextjs")
        assert "Guard: Guard.SomenteAdvogados" in output
        assert "enforced at pipeline route level" in output

    def test_no_guard_reference_when_absent(self, contrato_program):
        pulse = contrato_program.get_pulse("Notificar")
        output = generate_pulse_stub(pulse, contrato_program, "nextjs")
        assert "Guard:" not in output


# ============================================================
# Lens Stub Generator (Layer 3)
# ============================================================

class TestLensStubGenerator:
    def test_generates_component(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert "export default function Dashboard()" in output

    def test_table_has_entity(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert 'entity="Contrato"' in output

    def test_form_contains_button(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert "<FormComponent" in output
        assert "Analisar Risco</button>" in output
        assert "</FormComponent>" in output

    def test_button_has_trigger(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert 'trigger("ExtrairRisco")' in output
        assert 'trigger("GerarResumo")' in output

    def test_inject_html(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert "dangerouslySetInnerHTML" in output
        assert "LegalTech" in output

    def test_mood_comment(self, contrato_program):
        lens = contrato_program.lenses[0]
        output = generate_lens_stub(lens, "nextjs")
        assert "Mood: Clean, Legal-Tech, Professional" in output
