// Zod validators for Aluno
// Auto-generated by Epi Transpiler v0.3
// Epistemic fields: 1 (AI-inferred, runtime-validated)

import { z } from "zod";

export const AlunoNivelSchema = z.enum(["Iniciante", "Intermediario", "Avancado"]).optional();

export const AlunoEpistemicSchema = z.object({
  nivel: AlunoNivelSchema,
});

export type AlunoEpistemic = z.infer<typeof AlunoEpistemicSchema>;
