// Zod validators for Submissao
// Auto-generated by Epi Transpiler v0.3
// Epistemic fields: 3 (AI-inferred, runtime-validated)

import { z } from "zod";

export const SubmissaoAvaliacaoSchema = z.enum(["Correto", "Parcial", "Incorreto"]);
// Confidence schema — Epi v0.3 stochastic boundary
// AI output is accepted without human review only when confidence >= 0.85
export const SubmissaoAvaliacaoSchemaConfidence = z.object({
  value: z.enum(["Correto", "Parcial", "Incorreto"]),
  confidence: z.number().min(0).max(1),
  threshold: z.literal(0.85),
  requiresReview: z.boolean(),
});
export type SubmissaoAvaliacaoSchemaConfidenceType = z.infer<typeof SubmissaoAvaliacaoSchemaConfidence>;

export const SubmissaoConfiancaSchema = z.number().min(0).max(1);

export const SubmissaoComentarioSchema = z.string().max(800).min(1, "AI output must not be empty");

export const SubmissaoEpistemicSchema = z.object({
  avaliacao: SubmissaoAvaliacaoSchema,
  confianca: SubmissaoConfiancaSchema,
  comentario: SubmissaoComentarioSchema,
});

export type SubmissaoEpistemic = z.infer<typeof SubmissaoEpistemicSchema>;

// Bayesian update for Submissao.avaliacao
// Prior: {"Correto": 0.4, "Parcial": 0.45, "Incorreto": 0.15}
// Applies Bayes' theorem: posterior ∝ likelihood × prior
// Source: Dante Barone — Computação Estocástica
export function bayesianUpdateSubmissaoAvaliacao(
  likelihood: Record<"Correto" | "Parcial" | "Incorreto", number>
): { prediction: "Correto" | "Parcial" | "Incorreto"; confidence: number; posterior: Record<"Correto" | "Parcial" | "Incorreto", number>; requiresReview: boolean } {
  const prior: Record<"Correto" | "Parcial" | "Incorreto", number> = { "Correto": 0.4, "Parcial": 0.45, "Incorreto": 0.15 };

  // Compute unnormalized posterior: p(class|evidence) ∝ likelihood * prior
  const unnormalized = Object.keys(prior).reduce((acc, cls) => {
    acc[cls as "Correto" | "Parcial" | "Incorreto"] = likelihood[cls as "Correto" | "Parcial" | "Incorreto"] * prior[cls as "Correto" | "Parcial" | "Incorreto"];
    return acc;
  }, {} as Record<"Correto" | "Parcial" | "Incorreto", number>);

  // Normalize to get valid probability distribution
  const total = Object.values(unnormalized).reduce((s, v) => s + v, 0);
  const posterior = Object.keys(unnormalized).reduce((acc, cls) => {
    acc[cls as "Correto" | "Parcial" | "Incorreto"] = total > 0 ? unnormalized[cls as "Correto" | "Parcial" | "Incorreto"] / total : 1 / 3;
    return acc;
  }, {} as Record<"Correto" | "Parcial" | "Incorreto", number>);

  // Select most probable class
  const prediction = (Object.keys(posterior) as "Correto" | "Parcial" | "Incorreto"[]).reduce(
    (best, cls) => posterior[cls] > posterior[best] ? cls : best
  );
  const confidence = posterior[prediction];

  return {
    prediction,
    confidence,
    posterior,
    requiresReview: confidence < 0.85,
  };
}
