"""
Deterministic Generator: Guard → Middleware

Generates authentication/authorization middleware from Guard declarations.
"""

from __future__ import annotations

from epi.parser.ast_nodes import EpiProgram, Guard


def _generate_nextjs_middleware(guard: Guard) -> str:
    conditions = []
    for cond in guard.conditions:
        if "Auth.Role" in cond.left:
            conditions.append(
                f'  if (session?.user?.role !== "{cond.right}") {{\n'
                f"    return NextResponse.json({{ error: 'Forbidden' }}, {{ status: 403 }});\n"
                f"  }}"
            )
        else:
            conditions.append(
                f'  if (!(context.{cond.left} {cond.operator} "{cond.right}")) {{\n'
                f"    return NextResponse.json({{ error: 'Forbidden' }}, {{ status: 403 }});\n"
                f"  }}"
            )

    # Guard returns NextResponse (forbidden) or null (allowed).
    # The caller MUST check: const guard = await fn(session); if (guard) return guard;
    # This ensures execution stops immediately — previously the return inside the
    # helper function did not interrupt the calling route handler.
    return (
        f"// Guard: {guard.name}\n"
        f"// Auto-generated by Epi Transpiler v0.3\n"
        f"// Returns NextResponse(403) if forbidden, null if allowed.\n"
        f"// Usage in route: const g = {_to_camel(guard.name)}(session); if (g) return g;\n"
        f"import {{ NextResponse }} from 'next/server';\n"
        f"type Session = {{ user?: {{ role?: string }} }} | null;\n\n"
        f"export function {_to_camel(guard.name)}(session: Session): NextResponse | null {{\n"
        + "\n".join(conditions)
        + "\n  return null;\n}\n"
    )


def _generate_fastapi_dependency(guard: Guard) -> str:
    conditions = []
    for cond in guard.conditions:
        if "Auth.Role" in cond.left:
            conditions.append(
                f'    if current_user.role != "{cond.right}":\n'
                f'        raise HTTPException(status_code=403, detail="Forbidden")'
            )

    return (
        f"# Guard: {guard.name}\n"
        f"# Auto-generated by Epi Transpiler v0.3\n"
        f"async def {_to_snake(guard.name)}(\n"
        f"    current_user: User = Depends(get_current_user),\n"
        f") -> User:\n"
        + "\n".join(conditions)
        + "\n    return current_user\n"
    )


def generate_middleware(program: EpiProgram, target: str = "nextjs") -> dict[str, str]:
    """Generate middleware files for all guards. Returns {filename: content}."""
    result = {}
    for guard in program.guards:
        if target == "nextjs":
            filename = f"middleware/{_to_kebab(guard.name)}.ts"
            result[filename] = _generate_nextjs_middleware(guard)
        elif target == "fastapi":
            filename = f"dependencies/{_to_snake(guard.name)}.py"
            result[filename] = _generate_fastapi_dependency(guard)
    return result


def _to_camel(name: str) -> str:
    parts = name.split("_") if "_" in name else _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])


def _to_snake(name: str) -> str:
    parts = _split_pascal(name)
    return "_".join(p.lower() for p in parts)


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
