"""
Deterministic Generator: Entity → Prisma Schema

This generator handles RIGID types deterministically (template-based)
and marks EPISTEMIC fields with validation annotations.
"""

from __future__ import annotations

from epi.parser.ast_nodes import Entity, EpiProgram, EpistemicType, RigidType, TypeDomain

RIGID_TYPE_MAP = {
    "UUID": "String @id @default(uuid())",
    "Text": "String",
    "Int": "Int",
    "Float": "Float",
    "Decimal": "Decimal",
    "Bool": "Boolean",
    "DateTime": "DateTime",
    "JSON": "Json",
}


def _rigid_field_to_prisma(name: str, rigid: RigidType) -> str:
    base = RIGID_TYPE_MAP.get(rigid.base, "String")
    if "auto" in rigid.modifiers:
        if rigid.base == "UUID":
            base = "String @id @default(uuid())"
        elif rigid.base == "DateTime":
            base = "DateTime @default(now())"
    return f"  {name} {base}"


def _epistemic_field_to_prisma(name: str, epistemic: EpistemicType) -> str:
    """Epistemic fields are stored as strings/enums in DB, validated at runtime."""
    if epistemic.kind == "Enum" and epistemic.enum_values:
        return f"  {name} String // @epi:epistemic AI.Enum({', '.join(epistemic.enum_values)})"
    if epistemic.kind == "Score":
        return f"  {name} Float // @epi:epistemic AI.Score"
    if epistemic.kind == "Embedding":
        return f"  {name} Json // @epi:epistemic AI.Embedding"
    return f"  {name} String // @epi:epistemic AI.{epistemic.kind}"


def generate_prisma_entity(entity: Entity) -> str:
    lines = [f"model {entity.name} {{"]
    for field in entity.fields:
        if field.type.domain == TypeDomain.RIGID:
            lines.append(_rigid_field_to_prisma(field.name, field.type))
        else:
            lines.append(_epistemic_field_to_prisma(field.name, field.type))
    lines.append("}")
    return "\n".join(lines)


def generate_prisma(program: EpiProgram) -> str:
    """Generate complete Prisma schema from all entities in the program."""
    header = [
        "// Auto-generated by Epi Transpiler v0.2",
        "// DO NOT EDIT — regenerate from .epi source",
        "",
        "generator client {",
        '  provider = "prisma-client-js"',
        "}",
        "",
        "datasource db {",
        '  provider = "postgresql"',
        '  url      = env("DATABASE_URL")',
        "}",
        "",
    ]
    models = [generate_prisma_entity(e) for e in program.entities]
    return "\n".join(header) + "\n\n".join(models) + "\n"
