"""
Deterministic Generator: Pipeline → Routes

Generates route/endpoint orchestration from Pipeline declarations.
"""

from __future__ import annotations

from epi.parser.ast_nodes import EpiProgram, Pipeline


def _generate_nextjs_route(pipeline: Pipeline, program: EpiProgram) -> str:
    # Collect imports: pulse functions + guard middleware
    pulse_imports = []
    guard_imports = []
    seen_guards: set[str] = set()

    for step_name in pipeline.flow:
        pulse = program.get_pulse(step_name)
        pulse_imports.append(
            f"import {{ {_to_camel(step_name)} }} from '../../pulses/{_to_kebab(step_name)}';"
        )
        if pulse and pulse.guard_ref:
            guard_name = pulse.guard_ref.split(".")[-1]
            if guard_name not in seen_guards:
                seen_guards.add(guard_name)
                guard_imports.append(
                    f"import {{ {_to_camel(guard_name)} }} from '../../middleware/{_to_kebab(guard_name)}';"
                )

    all_imports = (
        "import { NextRequest, NextResponse } from 'next/server';\n"
        "import { getServerSession } from 'next-auth';\n"
        + "\n".join(guard_imports)
        + ("\n" if guard_imports else "")
        + "\n".join(pulse_imports)
    )

    # Build steps with result chaining
    steps = []
    prev_result = "input"
    for i, step_name in enumerate(pipeline.flow):
        pulse = program.get_pulse(step_name)
        guard_check = ""
        if pulse and pulse.guard_ref:
            guard_func = pulse.guard_ref.split(".")[-1]
            # Guard returns NextResponse|null — return early if forbidden
            guard_check = (
                f"    const _guard{i} = {_to_camel(guard_func)}(session);\n"
                f"    if (_guard{i}) return _guard{i};\n"
            )

        result_var = f"{_to_camel(step_name)}Result"
        steps.append(
            f"    // Step {i + 1}: {step_name}\n"
            f"{guard_check}"
            f"    const {result_var} = await {_to_camel(step_name)}({prev_result});"
        )
        prev_result = result_var

    flow_code = "\n\n".join(steps)

    # Error handling: wrap in try/catch with retry
    if pipeline.on_error and pipeline.on_error.strategy == "Retry":
        max_retries = pipeline.on_error.params.get("max", 3)
        backoff = pipeline.on_error.params.get("backoff", "fixed")
        return (
            f"// Pipeline: {pipeline.name}\n"
            f"// Auto-generated by Epi Transpiler v0.2\n"
            f"// Flow: {' -> '.join(pipeline.flow)}\n\n"
            f"{all_imports}\n\n"
            f"const MAX_RETRIES = {max_retries};\n\n"
            f"async function executePipeline(input: unknown, session: unknown) {{\n"
            f"{flow_code}\n\n"
            f"    return {prev_result};\n"
            f"}}\n\n"
            f"export async function POST(request: NextRequest) {{\n"
            f"  const input = await request.json();\n"
            f"  const session = await getServerSession();\n\n"
            f"  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {{\n"
            f"    try {{\n"
            f"      const result = await executePipeline(input, session);\n"
            f"      return NextResponse.json({{ success: true, data: result }});\n"
            f"    }} catch (error) {{\n"
            f"      if (attempt === MAX_RETRIES) {{\n"
            f"        return NextResponse.json(\n"
            f"          {{ error: 'Pipeline failed after retries', pipeline: '{pipeline.name}' }},\n"
            f"          {{ status: 500 }},\n"
            f"        );\n"
            f"      }}\n"
            + (f"      await new Promise(r => setTimeout(r, Math.pow(2, attempt) * 1000));\n" if backoff == "exponential" else f"      await new Promise(r => setTimeout(r, 1000));\n")
            + f"    }}\n"
            f"  }}\n"
            f"}}\n"
        )

    # No retry — simple try/catch
    return (
        f"// Pipeline: {pipeline.name}\n"
        f"// Auto-generated by Epi Transpiler v0.2\n"
        f"// Flow: {' -> '.join(pipeline.flow)}\n\n"
        f"{all_imports}\n\n"
        f"export async function POST(request: NextRequest) {{\n"
        f"  const input = await request.json();\n"
        f"  const session = await getServerSession();\n\n"
        f"  try {{\n"
        f"{flow_code}\n\n"
        f"    return NextResponse.json({{ success: true, data: {prev_result} }});\n"
        f"  }} catch (error) {{\n"
        f"    return NextResponse.json(\n"
        f"      {{ error: 'Pipeline failed', pipeline: '{pipeline.name}' }},\n"
        f"      {{ status: 500 }},\n"
        f"    );\n"
        f"  }}\n"
        f"}}\n"
    )


def generate_routes(program: EpiProgram, target: str = "nextjs") -> dict[str, str]:
    """Generate route files for all pipelines. Returns {filename: content}."""
    result = {}
    for pipeline in program.pipelines:
        if target == "nextjs":
            filename = f"app/api/{_to_kebab(pipeline.name)}/route.ts"
            result[filename] = _generate_nextjs_route(pipeline, program)
    return result


def _to_camel(name: str) -> str:
    parts = _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
