"""
Deterministic Generator: Pipeline → Routes

Generates route/endpoint orchestration from Pipeline declarations.
"""

from __future__ import annotations

from epi.parser.ast_nodes import EpiProgram, Pipeline


def _generate_nextjs_route(pipeline: Pipeline, program: EpiProgram) -> str:
    steps = []
    for step_name in pipeline.flow:
        pulse = program.get_pulse(step_name)
        guard_check = ""
        if pulse and pulse.guard_ref:
            guard_func = pulse.guard_ref.split(".")[-1]
            guard_check = f"  await {_to_camel(guard_func)}(session);\n"

        steps.append(
            f"  // Step: {step_name}\n"
            f"{guard_check}"
            f"  const {_to_camel(step_name)}Result = await {_to_camel(step_name)}(input);"
        )

    error_handling = ""
    if pipeline.on_error:
        if pipeline.on_error.strategy == "Retry":
            max_retries = pipeline.on_error.params.get("max", 3)
            error_handling = (
                f"  // Error strategy: Retry (max: {max_retries})\n"
                f"  // Implemented via retry wrapper"
            )

    flow_code = "\n\n".join(steps)

    return (
        f"// Pipeline: {pipeline.name}\n"
        f"// Auto-generated by Epi Transpiler v0.2\n"
        f"// Flow: {' -> '.join(pipeline.flow)}\n\n"
        f"import {{ NextRequest, NextResponse }} from 'next/server';\n\n"
        f"export async function POST(request: NextRequest) {{\n"
        f"  const input = await request.json();\n"
        f"  const session = await getServerSession();\n\n"
        f"{flow_code}\n\n"
        f"{error_handling}\n"
        f"  return NextResponse.json({{ success: true }});\n"
        f"}}\n"
    )


def generate_routes(program: EpiProgram, target: str = "nextjs") -> dict[str, str]:
    """Generate route files for all pipelines. Returns {filename: content}."""
    result = {}
    for pipeline in program.pipelines:
        if target == "nextjs":
            filename = f"app/api/{_to_kebab(pipeline.name)}/route.ts"
            result[filename] = _generate_nextjs_route(pipeline, program)
    return result


def _to_camel(name: str) -> str:
    parts = _split_pascal(name)
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
