"""
Deterministic Generator: Entity epistemic fields → Zod validation schemas

This is the critical proof of the Epistemic Type System:
a single AI.* type declaration generates BOTH the inference call (Layer 3)
AND the runtime validation schema (this module, Layer 2).

The validator constrains what the LLM is allowed to return.
If it compiles, it validates.
"""

from __future__ import annotations

from epi.parser.ast_nodes import Entity, EpiProgram, EpistemicType, TypeDomain


def generate_zod_schema(entity: Entity) -> str | None:
    """Generate a Zod validation schema for an Entity's epistemic fields.

    Returns None if the entity has no epistemic fields.
    """
    epistemic = entity.epistemic_fields
    if not epistemic:
        return None

    lines = [
        f"// Zod validators for {entity.name}",
        "// Auto-generated by Epi Transpiler v0.2",
        f"// Epistemic fields: {len(epistemic)} (AI-inferred, runtime-validated)",
        "",
        'import { z } from "zod";',
        "",
    ]

    for field in epistemic:
        schema = _epistemic_to_zod(field.name, field.type, entity.name)
        lines.append(schema)
        lines.append("")

    # Combined schema for all epistemic fields
    field_entries = []
    for field in epistemic:
        validator_name = f"{entity.name}{_to_pascal(field.name)}Schema"
        field_entries.append(f"  {field.name}: {validator_name},")

    lines.append(f"export const {entity.name}EpistemicSchema = z.object({{")
    lines.extend(field_entries)
    lines.append("});")
    lines.append("")
    lines.append(f"export type {entity.name}Epistemic = z.infer<typeof {entity.name}EpistemicSchema>;")
    lines.append("")

    return "\n".join(lines)


def _epistemic_to_zod(field_name: str, etype: EpistemicType, entity_name: str = "") -> str:
    schema_name = f"{entity_name}{_to_pascal(field_name)}Schema"

    if etype.kind == "Enum" and etype.enum_values:
        values = ", ".join(f'"{v}"' for v in etype.enum_values)
        schema = f"z.enum([{values}])"
        if etype.args.get("strict"):
            # strict mode: no .default(), no .optional()
            return f"export const {schema_name} = {schema};"
        return f"export const {schema_name} = {schema}.optional();"

    if etype.kind == "Text":
        max_tokens = etype.args.get("max_tokens")
        schema = "z.string()"
        if max_tokens:
            # Approximate: 1 token ≈ 4 chars
            max_chars = int(max_tokens) * 4
            schema += f".max({max_chars})"
        schema += '.min(1, "AI output must not be empty")'
        return f"export const {schema_name} = {schema};"

    if etype.kind == "Classification":
        labels = etype.args.get("labels", [])
        if isinstance(labels, list) and labels:
            values = ", ".join(f'"{v}"' for v in labels)
            return f"export const {schema_name} = z.enum([{values}]);"
        return f"export const {schema_name} = z.string().min(1);"

    if etype.kind == "Score":
        min_val = etype.args.get("min", 0)
        max_val = etype.args.get("max", 1)
        return f"export const {schema_name} = z.number().min({min_val}).max({max_val});"

    if etype.kind == "Embedding":
        dimensions = etype.args.get("dimensions")
        if dimensions:
            return f"export const {schema_name} = z.array(z.number()).length({dimensions});"
        return f"export const {schema_name} = z.array(z.number()).min(1);"

    # Fallback for unknown epistemic types
    return f"export const {schema_name} = z.string().min(1);"


def generate_validators(program: EpiProgram) -> dict[str, str]:
    """Generate Zod validator files for all entities with epistemic fields.

    Returns {filename: content}.
    """
    result = {}
    for entity in program.entities:
        schema = generate_zod_schema(entity)
        if schema:
            filename = f"validators/{_to_kebab(entity.name)}.ts"
            result[filename] = schema
    return result


def _to_pascal(name: str) -> str:
    return name[0].upper() + name[1:] if name else name


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
