"""
Deterministic Generator: Entity epistemic fields → Zod validation schemas

This is the critical proof of the Epistemic Type System:
a single AI.* type declaration generates BOTH the inference call (Layer 3)
AND the runtime validation schema (this module, Layer 2).

The validator constrains what the LLM is allowed to return.
If it compiles, it validates.

v0.3 additions (Dante Barone — Computação Estocástica):
- When AI.Enum has prior: Distribution(...), generates bayesianUpdate() helper
  that applies Bayes' theorem to combine prior beliefs with AI likelihood output.
- When confidence_threshold is set, generates a separate confidence schema
  that the Pulse layer uses to decide whether to trigger a Checkpoint.
"""

from __future__ import annotations

from epi.parser.ast_nodes import Entity, EpiProgram, EpistemicType, TypeDomain


def generate_zod_schema(entity: Entity) -> str | None:
    """Generate a Zod validation schema for an Entity's epistemic fields.

    Returns None if the entity has no epistemic fields.
    """
    epistemic = entity.epistemic_fields
    if not epistemic:
        return None

    lines = [
        f"// Zod validators for {entity.name}",
        "// Auto-generated by Epi Transpiler v0.3",
        f"// Epistemic fields: {len(epistemic)} (AI-inferred, runtime-validated)",
        "",
        'import { z } from "zod";',
        "",
    ]

    for field in epistemic:
        schema = _epistemic_to_zod(field.name, field.type, entity.name)
        lines.append(schema)
        lines.append("")

    # Combined schema for all epistemic fields
    field_entries = []
    for field in epistemic:
        validator_name = f"{entity.name}{_to_pascal(field.name)}Schema"
        field_entries.append(f"  {field.name}: {validator_name},")

    lines.append(f"export const {entity.name}EpistemicSchema = z.object({{")
    lines.extend(field_entries)
    lines.append("});")
    lines.append("")
    lines.append(f"export type {entity.name}Epistemic = z.infer<typeof {entity.name}EpistemicSchema>;")
    lines.append("")

    # v0.3: generate Bayesian helpers for fields with prior distributions
    bayes_helpers = _generate_bayesian_helpers(entity)
    if bayes_helpers:
        lines.append(bayes_helpers)

    return "\n".join(lines)


def _epistemic_to_zod(field_name: str, etype: EpistemicType, entity_name: str = "") -> str:
    schema_name = f"{entity_name}{_to_pascal(field_name)}Schema"

    if etype.kind == "Enum" and etype.enum_values:
        values = ", ".join(f'"{v}"' for v in etype.enum_values)
        schema = f"z.enum([{values}])"
        if etype.args.get("strict"):
            base = f"export const {schema_name} = {schema};"
        else:
            base = f"export const {schema_name} = {schema}.optional();"

        # v0.3: if confidence_threshold declared, add confidence companion schema
        if etype.confidence_threshold is not None:
            companion = (
                f"\n"
                f"// Confidence schema — Epi v0.3 stochastic boundary\n"
                f"// AI output is accepted without human review only when confidence >= {etype.confidence_threshold}\n"
                f"export const {schema_name}Confidence = z.object({{\n"
                f"  value: {schema},\n"
                f"  confidence: z.number().min(0).max(1),\n"
                f"  threshold: z.literal({etype.confidence_threshold}),\n"
                f"  requiresReview: z.boolean(),\n"
                f"}});\n"
                f"export type {schema_name}ConfidenceType = z.infer<typeof {schema_name}Confidence>;"
            )
            return base + companion
        return base

    if etype.kind == "Text":
        max_tokens = etype.args.get("max_tokens")
        schema = "z.string()"
        if max_tokens:
            # Approximate: 1 token ≈ 4 chars
            max_chars = int(max_tokens) * 4
            schema += f".max({max_chars})"
        schema += '.min(1, "AI output must not be empty")'
        return f"export const {schema_name} = {schema};"

    if etype.kind == "Classification":
        labels = etype.args.get("labels", [])
        if isinstance(labels, list) and labels:
            values = ", ".join(f'"{v}"' for v in labels)
            return f"export const {schema_name} = z.enum([{values}]);"
        return f"export const {schema_name} = z.string().min(1);"

    if etype.kind == "Score":
        min_val = etype.args.get("min", 0)
        max_val = etype.args.get("max", 1)
        return f"export const {schema_name} = z.number().min({min_val}).max({max_val});"

    if etype.kind == "Embedding":
        dimensions = etype.args.get("dimensions")
        if dimensions:
            return f"export const {schema_name} = z.array(z.number()).length({dimensions});"
        return f"export const {schema_name} = z.array(z.number()).min(1);"

    # Fallback for unknown epistemic types
    return f"export const {schema_name} = z.string().min(1);"


def _generate_bayesian_helpers(entity: Entity) -> str:
    """Generate bayesianUpdate() helpers for fields with prior distributions.

    Implements Bayes' theorem: P(class|evidence) ∝ P(evidence|class) * P(class)
    where P(class) is the declared prior and P(evidence|class) is the AI's
    raw probability output (likelihood).

    This directly addresses Dante Barone's feedback on Stochastic Computation:
    the prior encodes domain knowledge (e.g., class distribution in a school),
    and the posterior combines it with the AI's inference signal.
    """
    helpers = []

    for field in entity.epistemic_fields:
        etype = field.type
        if not isinstance(etype, EpistemicType):
            continue
        if not etype.prior:
            continue

        field_pascal = _to_pascal(field.name)
        helper_name = f"bayesianUpdate{entity.name}{field_pascal}"
        prior_entries = ", ".join(f'"{k}": {v}' for k, v in etype.prior.items())
        labels = list(etype.prior.keys())
        labels_type = " | ".join(f'"{l}"' for l in labels)

        confidence_threshold = etype.confidence_threshold or 0.7

        helpers.append(
            f"// Bayesian update for {entity.name}.{field.name}\n"
            f"// Prior: {{{prior_entries}}}\n"
            f"// Applies Bayes' theorem: posterior ∝ likelihood × prior\n"
            f"// Source: Dante Barone — Computação Estocástica\n"
            f"export function {helper_name}(\n"
            f"  likelihood: Record<{labels_type}, number>\n"
            f"): {{ prediction: {labels_type}; confidence: number; posterior: Record<{labels_type}, number>; requiresReview: boolean }} {{\n"
            f"  const prior: Record<{labels_type}, number> = {{ {prior_entries} }};\n"
            f"\n"
            f"  // Compute unnormalized posterior: p(class|evidence) ∝ likelihood * prior\n"
            f"  const unnormalized = Object.keys(prior).reduce((acc, cls) => {{\n"
            f"    acc[cls as {labels_type}] = likelihood[cls as {labels_type}] * prior[cls as {labels_type}];\n"
            f"    return acc;\n"
            f"  }}, {{}} as Record<{labels_type}, number>);\n"
            f"\n"
            f"  // Normalize to get valid probability distribution\n"
            f"  const total = Object.values(unnormalized).reduce((s, v) => s + v, 0);\n"
            f"  const posterior = Object.keys(unnormalized).reduce((acc, cls) => {{\n"
            f"    acc[cls as {labels_type}] = total > 0 ? unnormalized[cls as {labels_type}] / total : 1 / {len(labels)};\n"
            f"    return acc;\n"
            f"  }}, {{}} as Record<{labels_type}, number>);\n"
            f"\n"
            f"  // Select most probable class\n"
            f"  const prediction = (Object.keys(posterior) as {labels_type}[]).reduce(\n"
            f"    (best, cls) => posterior[cls] > posterior[best] ? cls : best\n"
            f"  );\n"
            f"  const confidence = posterior[prediction];\n"
            f"\n"
            f"  return {{\n"
            f"    prediction,\n"
            f"    confidence,\n"
            f"    posterior,\n"
            f"    requiresReview: confidence < {confidence_threshold},\n"
            f"  }};\n"
            f"}}\n"
        )

    return "\n".join(helpers)


def generate_validators(program: EpiProgram) -> dict[str, str]:
    """Generate Zod validator files for all entities with epistemic fields.

    Returns {filename: content}.
    """
    result = {}
    for entity in program.entities:
        schema = generate_zod_schema(entity)
        if schema:
            filename = f"validators/{_to_kebab(entity.name)}.ts"
            result[filename] = schema
    return result


def _to_pascal(name: str) -> str:
    return name[0].upper() + name[1:] if name else name


def _to_kebab(name: str) -> str:
    parts = _split_pascal(name)
    return "-".join(p.lower() for p in parts)


def _split_pascal(name: str) -> list[str]:
    parts = []
    current = ""
    for ch in name:
        if ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return parts
