// Trace: AvaliarResposta (Pulse: AvaliarRespostaAluno)
// Auto-generated by Epi Transpiler v0.3 (epistemic layer)
// Input: Submissao
// Checkpoint strategy: ReviewRequired

import Anthropic from "@anthropic-ai/sdk";
import { readFileSync } from "fs";
import { resolve } from "path";
import { randomUUID } from "crypto";
import { saveTrace, getTrace, updateTrace, TraceState } from "../../lib/trace-store";

const client = new Anthropic();

export interface AvaliarRespostaResult {
  traceId: string;
  status: "completed" | "paused";
  output?: unknown;
  exposedFields: Record<string, unknown>;
  confidence: number;
}

export async function executeAvaliarResposta(
  input: Submissao,
  previousContext?: unknown,
  sessionUserId?: string
): Promise<AvaliarRespostaResult> {
  const traceId = randomUUID();
  const CONFIDENCE_THRESHOLD = 0.85;

  saveTrace({
    traceId,
    pulseName: "AvaliarRespostaAluno",
    traceName: "AvaliarResposta",
    status: "running",
    exposedFields: {},
    confidence: 0,
    confidenceThreshold: CONFIDENCE_THRESHOLD,
    createdAt: new Date().toISOString(),
  });

  const promptPath = resolve(process.cwd(), "prompts/avaliar-pedagogicamente.md");
  const systemPrompt = readFileSync(promptPath, "utf-8") + "\n\nIMPORTANT: Your response MUST be valid JSON. Include a '_confidence' field (0.0-1.0) indicating your confidence in the output.";

  // Inject previous trace context if available
  const userContent = previousContext
    ? JSON.stringify({ input: input.resposta_aluno, context: previousContext })
    : JSON.stringify(input.resposta_aluno);

  let rawOutput: unknown;
  let confidence = 0;

  try {
    const response = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1024,
      temperature: 0.1,
      system: systemPrompt,
      messages: [{ role: "user", content: userContent }],
    });

    const text = response.content[0].type === "text" ? response.content[0].text : "{}";
    rawOutput = JSON.parse(text);

    // Extract _confidence (Epi epistemic contract)
    if (typeof (rawOutput as Record<string, unknown>)._confidence === "number") {
      confidence = (rawOutput as Record<string, unknown>)._confidence as number;
      delete (rawOutput as Record<string, unknown>)._confidence;
    }

  } catch (error) {
    console.error(`[Epi] Trace AvaliarResposta failed:`, error);
    updateTrace(traceId, { status: "error" });
    return { traceId, status: "paused", exposedFields: {}, confidence: 0 };
  }

  const exposedFields: Record<string, unknown> = {};

  const shouldPause = confidence < 0.85; // on_low_confidence

  if (shouldPause) {
    updateTrace(traceId, {
      status: "paused",
      exposedFields,
      confidence,
      rawOutput,
      pausedAt: new Date().toISOString(),
    });
    return { traceId, status: "paused", exposedFields, confidence };
  }

  updateTrace(traceId, {
    status: "completed",
    exposedFields,
    confidence,
    rawOutput,
  });
  return { traceId, status: "completed", output: rawOutput, exposedFields, confidence };
}
