// Resume route — Continue paused trace after human review
// Auto-generated by Epi Transpiler v0.3
// Authorized role: Professor
//
// POST /api/traces/avaliar-resposta-aluno/[traceId]/resume
// Body: { correction?: Record<string, unknown> }
//
// If correction is provided, it replaces the AI's raw output
// and becomes the context for the next Trace in the Pulse.
// If no correction, the original AI output is accepted as-is.

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { getTrace, updateTrace } from "../../../../../lib/trace-store";
import { executeCompreenderEnunciado } from "../../../../../traces/avaliar-resposta-aluno/compreender-enunciado";
import { executeAvaliarResposta } from "../../../../../traces/avaliar-resposta-aluno/avaliar-resposta";

export async function POST(
  request: NextRequest,
  { params }: { params: { traceId: string } }
) {
  const session = await getServerSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const state = getTrace(params.traceId);
  if (!state) {
    return NextResponse.json({ error: "Trace not found" }, { status: 404 });
  }
  if (state.status !== "paused") {
    return NextResponse.json({ error: "Trace is not paused", status: state.status }, { status: 400 });
  }

  const body = await request.json().catch(() => ({}));
  const correction = body.correction ?? null;
  const resumedBy = (session as { user?: { email?: string } }).user?.email ?? "unknown";

  // Accept correction or original AI output
  const acceptedOutput = correction ?? state.rawOutput;

  updateTrace(params.traceId, {
    status: "completed",
    resumedBy,
    humanCorrection: correction ?? undefined,
  });

  return NextResponse.json({
    success: true,
    traceId: params.traceId,
    resumedBy,
    acceptedOutput,
    corrected: correction !== null,
  });
}
