"""
Scaffold Generator — creates project configuration files for Epi-generated projects.

These files are the boilerplate that any Next.js + Prisma + Anthropic project needs
to run. Without them, users would have to manually create package.json, tsconfig, etc.
"""

from __future__ import annotations

import json

from epi.parser.ast_nodes import EpiProgram


def generate_package_json(program: EpiProgram) -> str:
    name = next(
        (m.value for m in program.metadata if m.key.lower() == "name"),
        "epi-generated-app",
    )
    # Normalize to valid npm package name
    name = name.lower().replace(" ", "-").replace("_", "-")

    pkg = {
        "name": name,
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "postinstall": "prisma generate",
        },
        "dependencies": {
            "@anthropic-ai/sdk": "^0.39.0",
            "@prisma/client": "^5.22.0",
            "next": "^15.0.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
        },
        "devDependencies": {
            "@types/node": "^22.0.0",
            "@types/react": "^18.3.0",
            "@types/react-dom": "^18.3.0",
            "prisma": "^5.22.0",
            "typescript": "^5.6.0",
        },
    }
    return json.dumps(pkg, indent=2) + "\n"


def generate_tsconfig() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {
                "@/*": ["./*"],
            },
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }
    return json.dumps(config, indent=2) + "\n"


def generate_next_config() -> str:
    return """\
/** @type {import('next').NextConfig} */
const nextConfig = {
  // Generated by Epi Transpiler
};

module.exports = nextConfig;
"""


def generate_env_example() -> str:
    return """\
# Epi Generated Project — copy to .env and fill in your values

# PostgreSQL connection string
DATABASE_URL=postgresql://user:password@localhost:5432/dbname

# Anthropic API key — get yours at https://console.anthropic.com/keys
ANTHROPIC_API_KEY=sk-ant-...

# Next.js public URL (optional)
NEXT_PUBLIC_API_URL=http://localhost:3000
"""


def generate_gitignore() -> str:
    return """\
# Dependencies
node_modules/
.pnp
.pnp.js

# Next.js
.next/
out/

# Production
build/
dist/

# Environment
.env
.env.local
.env.*.local

# Prisma generated
prisma/generated/

# Logs
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db
"""


def generate_readme(program: EpiProgram, target: str) -> str:
    name = next(
        (m.value for m in program.metadata if m.key.lower() == "name"),
        "Epi Generated App",
    )
    framework = "Next.js + Prisma + Anthropic SDK" if target == "nextjs" else "FastAPI + Prisma + Anthropic SDK"
    return f"""\
# {name}

Generated by [Epi Transpiler](https://github.com/RandMelville/epi-lang) v0.3.

## Stack

{framework}

## Setup

```bash
# 1. Install dependencies
npm install

# 2. Configure environment
cp .env.example .env
# Edit .env and set DATABASE_URL and ANTHROPIC_API_KEY

# 3. Initialize database
npx prisma migrate dev --name init

# 4. Run development server
npm run dev
```

## Project Structure

```
├── app/api/          # Next.js API routes (generated from Pipelines)
├── middleware/       # Auth guards (generated from Guards)
├── pulses/           # AI inference functions (generated from Pulses)
├── components/       # UI components (generated from Lenses)
├── validators/       # Zod schemas for epistemic type validation
├── lib/              # Trace infrastructure (inspect/resume)
├── prompts/          # Prompt files referenced by Pulses
└── prisma/           # Database schema (generated from Entities)
```

## Epistemic Types

This project uses the Epi Epistemic Type System. AI-inferred fields are validated
at runtime via Zod schemas in `validators/`. See [SPEC.md](https://github.com/RandMelville/epi-lang/blob/main/SPEC.md).
"""
