"""
Scaffold Generator — creates project configuration files for Epi-generated projects.

These files are the boilerplate that any Next.js + Prisma + Anthropic project needs
to run. Without them, users would have to manually create package.json, tsconfig, etc.
"""

from __future__ import annotations

import json

from epi.parser.ast_nodes import EpiProgram


def generate_package_json(program: EpiProgram) -> str:
    name = next(
        (m.value for m in program.metadata if m.key.lower() == "name"),
        "epi-generated-app",
    )
    # Normalize to valid npm package name
    name = name.lower().replace(" ", "-").replace("_", "-")

    pkg = {
        "name": name,
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "postinstall": "prisma generate",
        },
        "dependencies": {
            "@anthropic-ai/sdk": "^0.39.0",
            "@prisma/client": "^5.22.0",
            "next": "^15.0.0",
            "openai": "^4.77.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
        },
        "devDependencies": {
            "@types/node": "^22.0.0",
            "@types/react": "^18.3.0",
            "@types/react-dom": "^18.3.0",
            "prisma": "^5.22.0",
            "typescript": "^5.6.0",
        },
    }
    return json.dumps(pkg, indent=2) + "\n"


def generate_tsconfig() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {
                "@/*": ["./*"],
            },
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }
    return json.dumps(config, indent=2) + "\n"


def generate_next_config() -> str:
    return """\
/** @type {import('next').NextConfig} */
const nextConfig = {
  // Generated by Epi Transpiler
};

module.exports = nextConfig;
"""


def generate_env_example() -> str:
    return """\
# Epi Generated Project — copy to .env and fill in your values

# PostgreSQL connection string
DATABASE_URL=postgresql://user:password@localhost:5432/dbname

# ---- LLM provider configuration ----
# Choose ONE of the blocks below.

# Option A — Anthropic (cloud, requires API key)
EPI_AI_PROVIDER=anthropic
EPI_AI_MODEL=claude-sonnet-4-20250514
ANTHROPIC_API_KEY=sk-ant-...

# Option B — Ollama (local, no API key, requires `ollama serve` running)
# EPI_AI_PROVIDER=ollama
# EPI_AI_MODEL=qwen2.5:3b-instruct
# EPI_AI_BASE_URL=http://localhost:11434/v1

# Next.js public URL (optional)
NEXT_PUBLIC_API_URL=http://localhost:3000
"""


def generate_llm_client() -> str:
    """Generate lib/llm-client.ts — provider-agnostic LLM client.

    Reads env vars EPI_AI_PROVIDER (anthropic|ollama), EPI_AI_MODEL, EPI_AI_BASE_URL.
    Both providers expose a uniform `llmCall()` interface, so Pulses/Traces are
    provider-independent at the call site.
    """
    return """\
// Provider-agnostic LLM client
// Auto-generated by Epi Transpiler v0.3
//
// Reads runtime env vars:
//   EPI_AI_PROVIDER : "anthropic" | "ollama"          (default: "anthropic")
//   EPI_AI_MODEL    : model identifier                (provider-specific default)
//   EPI_AI_BASE_URL : OpenAI-compatible endpoint URL  (only used for ollama)
//
// The Epi epistemic contract requires JSON output with a `_confidence` field
// (0.0–1.0). Both branches enforce JSON response_format where supported.

import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";

export interface LLMCallParams {
  systemPrompt: string;
  userContent: string;
  maxTokens: number;
  temperature: number;
}

export interface LLMResponse {
  text: string;
}

const provider = (process.env.EPI_AI_PROVIDER || "anthropic").toLowerCase();
const model =
  process.env.EPI_AI_MODEL ||
  (provider === "ollama" ? "qwen2.5:3b-instruct" : "claude-sonnet-4-20250514");
const baseURL =
  process.env.EPI_AI_BASE_URL ||
  (provider === "ollama" ? "http://localhost:11434/v1" : undefined);

let anthropicClient: Anthropic | null = null;
let openaiClient: OpenAI | null = null;

if (provider === "anthropic") {
  anthropicClient = new Anthropic();
} else if (provider === "ollama" || provider === "openai") {
  openaiClient = new OpenAI({
    baseURL,
    // Ollama ignores the key but the SDK requires a non-empty string.
    apiKey: process.env.OPENAI_API_KEY || "ollama",
  });
} else {
  throw new Error(
    `[Epi] Unknown EPI_AI_PROVIDER: "${provider}". Use "anthropic", "ollama", or "openai".`
  );
}

export async function llmCall(params: LLMCallParams): Promise<LLMResponse> {
  if (provider === "anthropic" && anthropicClient) {
    const response = await anthropicClient.messages.create({
      model,
      max_tokens: params.maxTokens,
      temperature: params.temperature,
      system: params.systemPrompt,
      messages: [{ role: "user", content: params.userContent }],
    });
    const text =
      response.content[0].type === "text" ? response.content[0].text : "{}";
    return { text };
  }

  if (openaiClient) {
    const response = await openaiClient.chat.completions.create({
      model,
      max_tokens: params.maxTokens,
      temperature: params.temperature,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: params.systemPrompt },
        { role: "user", content: params.userContent },
      ],
    });
    const text = response.choices[0].message.content || "{}";
    return { text };
  }

  throw new Error("[Epi] LLM client not initialized.");
}

export const epiLLMProvider = provider;
export const epiLLMModel = model;
"""


def generate_gitignore() -> str:
    return """\
# Dependencies
node_modules/
.pnp
.pnp.js

# Next.js
.next/
out/

# Production
build/
dist/

# Environment
.env
.env.local
.env.*.local

# Prisma generated
prisma/generated/

# Logs
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db
"""


def generate_readme(program: EpiProgram, target: str) -> str:
    name = next(
        (m.value for m in program.metadata if m.key.lower() == "name"),
        "Epi Generated App",
    )
    framework = "Next.js + Prisma + Anthropic SDK" if target == "nextjs" else "FastAPI + Prisma + Anthropic SDK"
    return f"""\
# {name}

Generated by [Epi Transpiler](https://github.com/RandMelville/epi-lang) v0.3.

## Stack

{framework}

## Setup

```bash
# 1. Install dependencies
npm install

# 2. Configure environment
cp .env.example .env
# Edit .env and set DATABASE_URL and ANTHROPIC_API_KEY

# 3. Initialize database
npx prisma migrate dev --name init

# 4. Run development server
npm run dev
```

## Project Structure

```
├── app/api/          # Next.js API routes (generated from Pipelines)
├── middleware/       # Auth guards (generated from Guards)
├── pulses/           # AI inference functions (generated from Pulses)
├── components/       # UI components (generated from Lenses)
├── validators/       # Zod schemas for epistemic type validation
├── lib/              # Trace infrastructure (inspect/resume)
├── prompts/          # Prompt files referenced by Pulses
└── prisma/           # Database schema (generated from Entities)
```

## Epistemic Types

This project uses the Epi Epistemic Type System. AI-inferred fields are validated
at runtime via Zod schemas in `validators/`. See [SPEC.md](https://github.com/RandMelville/epi-lang/blob/main/docs/SPEC.md).
"""
