// lib/trace-store.ts
// Auto-generated by Epi Transpiler v0.3
//
// In-memory trace state store for epistemic checkpoints.
// PRODUCTION NOTE: Replace Map with Redis (ioredis) or a Prisma model.
// The interface contract (saveTrace, getTrace, updateTrace) stays the same.

export interface TraceState {
  traceId: string;
  pulseName: string;
  traceName: string;
  status: "running" | "paused" | "completed" | "error";
  /** Fields declared in Expose: — surfaced for human inspection */
  exposedFields: Record<string, unknown>;
  /** Raw AI output before any correction */
  rawOutput?: unknown;
  /** Confidence extracted from AI response (0.0 – 1.0) */
  confidence: number;
  /** Threshold below which this trace was paused */
  confidenceThreshold?: number;
  pausedAt?: string;
  /** User ID of the reviewer who approved/corrected */
  resumedBy?: string;
  /** Human correction injected as context into the next trace */
  humanCorrection?: Record<string, unknown>;
  createdAt: string;
}

const store = new Map<string, TraceState>();

export function saveTrace(state: TraceState): void {
  store.set(state.traceId, state);
}

export function getTrace(traceId: string): TraceState | undefined {
  return store.get(traceId);
}

export function updateTrace(traceId: string, patch: Partial<TraceState>): void {
  const existing = store.get(traceId);
  if (existing) {
    store.set(traceId, { ...existing, ...patch });
  }
}

export function listPausedTraces(pulseName?: string): TraceState[] {
  return Array.from(store.values()).filter(
    (s) => s.status === "paused" && (!pulseName || s.pulseName === pulseName)
  );
}
